# Common Mage Cards
mage_commons = [
    "Comet Rune",
    "Crowdsource",
    "Echo Rune",
    "Fractal Whip",
    "Hellfire Rune",
    "Lightning",
    "Sucker Bolt",
    "Volcanic Lightning",
    "Cold Arm",
    "Erudition",
    "Grimoire",
    "Kugi",
    "Link",
    "Teleport",
    "Unpack the Bag",
    "Ascendance",
    "Bolt the Bolted",
    "Cheat",
    "Chilly Blow",
    "Equilibrium",
    "Ice Fort",
    "Incantation",
    "Iron Will",
    "Magic Marker",
    "Mana Shield",
    "Mental Wall",
    "Rewrite",
    "Shuffle",
    "Sweep",
]

# Rare Mage Cards
mage_rares = [
    "Bat Bolt",
    "Blood Surge",
    "Harpoon Bolt",
    "Inferno",
    "Meteor Strike",
    "Nova",
    "Reforge Weakness",
    "Rune of Ice",
    "Rune of Thunder",
    "Zap",
    "Final Word",
    "Maelstrom",
    "Ritual Channeling",
    "Scroll of Thorns",
    "Ascendance",
    "Bolt the Bolted",
    "Cheat",
    "Chilly Blow",
    "Equilibrium",
    "Ice Fort",
    "Incantation",
    "Iron Will",
    "Magic Marker",
    "Mana Shield",
    "Mental Wall",
    "Rewrite",
    "Shuffle",
    "Sweep",
    "Bolt Hell",
    "Channel Pain",
    "Chaos Rune",
    "Ethernal Return",
    "Glass Shrike",
    "Hearteater Bolt",
    "Ostracon",
    "Outburst",
    "Outside the Box",
    "Shatter",
    "Sunray Rune",
    "Vitruvian Mage",
    "Wind Blast",
    "Cyclone",
]

# Legendary Mage Cards
mage_legendary = [
    "Bolt Hell",
    "Channel Pain",
    "Chaos Rune",
    "Ethernal Return",
    "Glass Shrike",
    "Hearteater Bolt",
    "Ostracon",
    "Outburst",
    "Outside the Box",
    "Shatter",
    "Sunray Rune",
    "Vitruvian Mage",
    "Wind Blast",
    "Cyclone",
    "Arcane wager",
    "Botaoshi",
    "Brand of Doom",
    "Eternal Winter",
    "Excession",
    "Gallstones",
    "Infuse",
    "Mimic",
    "Paper Library",
    "Purify",
    "Simulacrum",
    "Triage",
    "Weave Laylines",
    "Final Word",
    "Scroll of Mind",
    "Scroll of Wall",
    "Aether Splash",
    "Anamnesis",
    "Bookmark",
    "Dark Pact",
    "Feedback Loop",
    "Grit",
    "Midnight Oil",
    "Occult Ritual",
    "Paper Recycle",
    "Subzero",
]

mage_starters = ["Magic Bolt", "Ethereal Shield"]
