# Common Rogue Cards
rogue_commons = [
    "Caltrops",
    "Clockwork Arrow",
    "Improvise",
    "Mordhau",
    "Rogue Tactics",
    "Shakedown",
    "Bonk",
    "Bottomless Purse",
    "Cover",
    "Death Mark",
    "Eagle Trick",
    "Kick",
    "Loaded Die",
    "Luck",
    "Osoto Gari",
    "Payback",
    "Quiver",
    "Teamwork",
    "Buster Bomb",
    "Eagle's Eye",
    "Knockback",
    "Mastery",
    "Precision Bomb",
]

# Rare Rogue Cards
rogue_rares = [
    "Blindsided",
    "Hamstring",
    "Lash Out",
    "Multi Arrow",
    "Rogue Knuckles",
    "Scissor Strike",
    "Sharp Rain",
    "Sick & Tired Arrow",
    "Throw Knives",
    "Trickle Down",
    "Adapt",
    "Bling",
    "Chainshirt",
    "Cornucopia",
    "Diversify",
    "Enchufla",
    "Entrench",
    "Flash",
    "Fortify",
    "Gancho",
    "Mad Skills",
    "Overexertion",
    "Paint Balloon",
    "Persevere",
    "Risky Draw",
    "Salve",
    "Backflip",
    "Bouncy Bomb",
    "Breath Control",
    "Damocles' Sword",
    "Deadly Roulette",
    "Flashbang Bomb",
    "Garbage Day",
    "Ivy Extract",
    "Perfect Balance",
    "Too Old For This",
]

# Legendary Rogue Cards
rogue_legendary = [
    "Arrow Split",
    "Barrage",
    "Chain Shot",
    "Deflect",
    "Minesweep",
    "Piercing Arrow",
    "Shrapnel",
    "Shredder Strike",
    "Stonks",
    "Violence",
    "Concussive Arrow",
    "Talon Arrow",
    "Battle Snack",
    "Bulwark",
    "Clothesline",
    "Clout",
    "Copycat",
    "Dig",
    "Emergency Tonic",
    "Finesse",
    "Hired Help",
    "Keeping Distance",
    "Marked Deck",
    "Not Today",
    "Rallying Cry",
    "Secret Stash",
    "Speed",
    "Tinker",
    "Vanish",
    "Ignite",
    "Bargain",
    "Deadly Streak",
    "Forgery Kit",
    "Hot Potato",
    "Maximum Effort",
    "Porcupine",
    "Shadow Stance",
    "Shockwave Bomb",
    "Sleeve Trick",
    "Wildcard",
]

rogue_starters = [
    "Sharp Arrow",
    "Buckler",
]
